import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Jotion",
  description: "Generated by Jotion",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/next.svg",
        href: "/next.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/next.svg",
        href: "/next.svg",
      }
    ]
  }
};

